branches:
  only:
  - master
  - dev
  - staging
  - hotfix
env:
  - COLUMNS=80
addons:
  apt:
    packages:
      - pandoc
dist: trusty
notifications:
  email:
    on_success: always
    on_failure: always
language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install coveralls
script:
  - coverage run --source=agutil --omit=*__init__.py -m unittest discover -v
  - pycodestyle agutil/*
after_success:
  - coveralls
before_deploy:
  - pandoc --from markdown --to rst README.md -o README.rst
deploy:
  skip_cleanup: true
  provider: pypi
  user: agraubert
  password:
    secure: FHfVn5sGSHQHiirQ8pcpG5vWtPgw/JTtPY2aoFxp7foUqqI1Ky6zC/Ze04OnSdOH/BBbHgtQobL7M4PFP3RiZyBcc9Aku7iXyn3c41rBweNpLLQG9xWJOu4WqpGkqV7w1zCjL8J14XP1ChnNL9+ZmfXA4eldy2GXe5VXK5EfhLYr843Z8edwVESnDxOjsK/NL23f9mZLdz/vFHKwAnh3398vFKUEXLV5GnSqPCZMjhhkd5C+K3SI2xR9MFQm4+qnueFJtRqDjkiDX5lyc5z1DprTnxjhMNjYECXdpoa3UIdc1AXOn4q0F2v6Es6Xc4XIIYTFuBwxWT88e6x9qJ3rkQ7QXl/Y7uMstphtzsWlvkdO+5S3YBv+QvZbK4OEJh/QUmVtUzecqvxJ4pGhmoT3o63FmToeTWlrL+zmLgC+/QjMsL/d2ANO28rAN37XT/OuQy/JyFVi+QRsw39ZGr6HvKFoDRWTRRMx0eXzjKgoW6QcsvbxnnAL7lZmTJA4wnuLE87iqonV55TPronYUi5Tk9GfFU0ZjdJEEJxCTPZDrYJlmny4JkED3kIqtWBDTZtghfA5ZPf3aP0MEaFHKJSSzJnSqCjtwbnKigOgxW6G8mT/bybR9KPY3yHIs0TWVySlcXkuol1iiHlKM6BvC8XlBP/R76QHcd4n+0Cm0TiHakI=
  on:
    branch: master
    python: 3.6
  distributions: sdist bdist_wheel
