branches:
  only:
  - master
  - dev
notifications:
  email:
    on_success: always
    on_failure: always
language: python
python:
- '3.5'
install: true
script:
- python3 -m unittest discover -v -s tests
deploy:
  provider: pypi
  user: agraubert
  password:
    secure: P/35pw+Eqvh+B9nISt/bBb0MTz6/5MMe1yh0Qy2BhKhPAixGI2RlXYYmylGMT1uC+JGHJFp4s1mbLEBmn1RYxcCedSwkZDFFRVJuVmbsWZHnT7vqQfSzq2QZtWNgaitJ6lyvvLpbhAWv0xex/ZVqgzG54X61wvlPuQxZY7HE1XS10f3sfpf3SjALl2vpsAodWBSroq49OiwkR2F1IdscpNG7OvMbvrNT6dRueJNik+fLbAxcdQYuDMWdQLwycKI/jXBLwf5LUEDnke4yFWHURgTcFmZbLLprg0tMgi8K0tBmMchzyn4cpq263tWE+kffaoRrVSSrIL8Op/q4QzrXXA4I5hiZEi2MamPDDNpWJH7Z8CXZpBquzfe/EtusMHS9h5vl5GfmvzmB0l/L0Xqmjh8powbSisZKRnxfFwmbryzeViqvQBODqXh+0BBsJDo5egLXNwbG/yNLWaq5lRYouQMJa11Ym2W3pcYozbQ2meI2Ww5Y+l9hpRHFtwMVae0W8K5tk854j8k1A9elHdMQ3JMkclZFrgXzVl1+FPKMdpeb+eyNyQa7H2D78w69crwlJ9n/td8q9mUTp1NwbEAJ33lQj8dM7TgFoobHIqjODkI7YmnXtsR2HX2GAhUIv/6TjDgJDgx1oIRON4Nf2/zHMBu8J3rNkjT+mKLUV+e18co=
  on:
    branch: master
